# Generated by Django 2.2.7 on 2019-11-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycheckout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customertype',
            options={'ordering': ['order'], 'verbose_name': '4 - customer type', 'verbose_name_plural': '4 - customer types'},
        ),
        migrations.AddField(
            model_name='customertype',
            name='information',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Information'),
        ),
        migrations.AddField(
            model_name='customertype',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
