# Generated by Django 2.2.7 on 2019-12-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycheckout', '0002_auto_20191127_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertype',
            name='price',
            field=models.FloatField(blank=True, help_text='Price', null=True, verbose_name='price'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
