# Generated by Django 2.2.7 on 2019-12-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycheckout', '0003_auto_20191214_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoir',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
