# Generated by Django 2.2.7 on 2019-12-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycheckout', '0005_avoir_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avoir',
            options={'verbose_name': 'Avoir', 'verbose_name_plural': 'Avoirs'},
        ),
        migrations.RemoveField(
            model_name='avoir',
            name='created_on',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='is_cancelled'),
        ),
    ]
