# Generated by Django 2.2.7 on 2020-01-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycheckout', '0008_auto_20191230_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total en euros', max_digits=5, null=True, verbose_name='Caisse en fin de journée'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_A',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total en euros', max_digits=5, null=True, verbose_name='Total Riquet'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_B',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total en euros', max_digits=5, null=True, verbose_name='Total Fonserane'),
        ),
    ]
