# Generated by Django 2.2.7 on 2020-01-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycheckout', '0009_auto_20200104_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Price'),
        ),
    ]
