# Generated by Django 2.2.7 on 2020-01-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycheckout', '0010_auto_20200104_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total', max_digits=5, null=True, verbose_name='Total'),
        ),
    ]
