# Generated by Django 2.2.7 on 2020-01-05 12:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycheckout', '0011_auto_20200104_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_cash',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total en euros', max_digits=5, null=True, verbose_name='Total liquide'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_cb',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total en euros', max_digits=5, null=True, verbose_name='Total cb'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_check',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total en euros', max_digits=5, null=True, verbose_name='Total chèques'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_office',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total en euros', max_digits=5, null=True, verbose_name='Total office'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_tourism',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total en euros', max_digits=5, null=True, verbose_name='Total chèques vacances'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_voucher',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total en euros', max_digits=5, null=True, verbose_name='Total vouchers'),
        ),
    ]
