# Generated by Django 2.2.7 on 2020-01-08 14:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycheckout', '0012_auto_20200105_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='start',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total en euros', max_digits=5, null=True, verbose_name='Caisse au départ'),
        ),
    ]
