# Generated by Django 2.2.7 on 2020-01-11 11:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easycheckout', '0013_auto_20200108_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': ' order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easycheckout.Checkout', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total en euros', max_digits=5, null=True, verbose_name='Caisse actuelle'),
        ),
    ]
