# Generated by Django 2.2.7 on 2020-01-12 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easycheckout', '0014_auto_20200111_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketSettings',
        ),
        migrations.RemoveField(
            model_name='avoir',
            name='year',
        ),
        migrations.AddField(
            model_name='avoir',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easycheckout.Checkout', verbose_name='checkout'),
        ),
    ]
