# Generated by Django 2.2.7 on 2019-11-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service title', max_length=100, verbose_name='title')),
                ('slug', models.CharField(help_text='Slug', max_length=100, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service title', max_length=100, verbose_name='title')),
                ('slug', models.CharField(help_text='Slug', max_length=100, verbose_name='slug')),
                ('total_capacity', models.IntegerField(blank=True, help_text='Train total capacity', null=True, verbose_name='total capacity')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('ride', models.ForeignKey(help_text='Choose a ride', on_delete=django.db.models.deletion.CASCADE, to='train.Ride', verbose_name='ride')),
            ],
            options={
                'verbose_name': '2 - train',
                'verbose_name_plural': '2 - trains',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_on', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('total_capacity', models.IntegerField(blank=True, help_text='Train total capacity', null=True, verbose_name='total capacity')),
                ('actual_capacity', models.IntegerField(blank=True, default=0, help_text='Actual train capacity', null=True, verbose_name='actual capacity')),
                ('train', models.ForeignKey(help_text='Choose a train', on_delete=django.db.models.deletion.CASCADE, to='train.Train', verbose_name='train')),
            ],
            options={
                'verbose_name': '7 - capacity',
                'verbose_name_plural': '7 - capacities',
                'ordering': ['date_on'],
            },
        ),
    ]
