# Generated by Django 2.2.7 on 2019-11-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('slug', models.CharField(help_text='Slug', max_length=100, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('selected', models.BooleanField(default=False, verbose_name='is selected')),
            ],
            options={
                'verbose_name': '3 - lieu de départ',
                'verbose_name_plural': '3 - lieux de départs',
            },
        ),
    ]
