# Generated by Django 2.2.7 on 2019-11-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='departure',
            field=models.ForeignKey(blank=True, help_text='lieu de départ', null=True, on_delete=django.db.models.deletion.CASCADE, to='train.Departure', verbose_name='departure'),
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_hour',
            field=models.CharField(blank=True, help_text='heure de départ', max_length=150, null=True, verbose_name='departure_hour'),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='is_selected'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='total_capacity',
            field=models.IntegerField(blank=True, default=60, help_text='Train total capacity', null=True, verbose_name='total capacity'),
        ),
    ]
